name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  path:  # id of input
    description: 'Path to fingerprint file'
    default: './.expo/fingerprint.json'
  project-path:  # id of input
    description: 'Path to project to fingerprint'
    default: './'
outputs:
  project-fingerprint: # id of output
    description: 'The stored fingerprint hash of the project'
  current-fingerprint:
    description: 'The fingerprint hash of the project now'
  matches:
    description: 'Whether the fingerprints match'
runs:
  using: 'node16'
  main: 'index.js'
