name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  path:  # id of input
    description: 'Path to fingerprint file'
    default: './.expo/fingerprint.json'
outputs:
  fingerprint: # id of output
    description: 'The fingerprint hash'
runs:
  using: 'node16'
  main: 'index.js'
